name: icu-survival
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - lifelines
  - scikit-survival
  - jupyterlab
  - wandb
  - shap
  - pydantic
  - ipywidgets
  - pip